name: Deploy Preview

# WARNING: This workflow uses pull_request_target which runs with repository secrets.
# Careful review of PR changes is required before approval.
on:
  pull_request_target:
    branches: [ main, dev ]
    types: [opened, synchronize, reopened]

# Specific permissions granted only where needed
permissions:
  contents: read       # Required for checkout
  packages: read      # Required for package installation
  pull-requests: read # Required for PR information

# Cancel redundant runs with specific PR identifier
concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  NODE_ENV: development
  HUSKY: 0  # Disabled to prevent git hooks during CI
  # Required environment variables validation
  REQUIRED_SECRETS: >-
    VERCEL_TOKEN
    VERCEL_ORG_ID
    VERCEL_PROJECT_ID
    DERIV_API_TOKEN
    DERIV_APP_ID

jobs:
  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging jobs
    permissions:
      pull-requests: read
    outputs:
      is-fork: ${{ steps.check.outputs.is-fork }}
      is-authorized: ${{ steps.check.outputs.is-authorized }}
      security-passed: ${{ steps.validate.outputs.passed }}
    steps:
      - name: Validate Required Secrets
        id: validate
        run: |
          missing_secrets=()
          for secret in $REQUIRED_SECRETS; do
            if [ -z "${!secret}" ]; then
              missing_secrets+=($secret)
            fi
          done
          
          if [ ${#missing_secrets[@]} -ne 0 ]; then
            echo "Missing required secrets: ${missing_secrets[*]}"
            echo "passed=false" >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "passed=true" >> $GITHUB_OUTPUT
      - name: Check PR source and permissions
        id: check
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const isFork = pr.head.repo.full_name !== pr.base.repo.full_name;
            
            // Check if PR author has write access or is a collaborator
            let isAuthorized = false;
            try {
              const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: pr.user.login
              });
              isAuthorized = ['admin', 'write'].includes(permission.permission);
            } catch (e) {
              isAuthorized = false;
            }
            
            core.setOutput('is-fork', isFork.toString());
            core.setOutput('is-authorized', isAuthorized.toString());
            
            if (isFork && !isAuthorized) {
              core.notice('⚠️ This PR is from a fork and requires approval from maintainers');
            }

  preview:
    name: Deploy Preview
    needs: security-check
    runs-on: ubuntu-latest
    # Run only after approval for first-time contributors from forks
    if: |
      github.event.workflow_run.conclusion != 'action_required' ||
      github.event.workflow_run.conclusion == 'approved'
    environment:
      name: preview
      url: ${{ steps.preview-url.outputs.url }}
    permissions:
      deployments: write
      issues: write
      pull-requests: write
      contents: read  # Needed for checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch all history for all tags and branches
          fetch-depth: 0
      
      # Enhanced security checks for fork PRs
      - name: Additional security checks for forks
        id: security_checks
        if: needs.security-check.outputs.is-fork == 'true'
        run: |
          # Check file size limits
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | while read file; do
            if [ -f "$file" ]; then
              size=$(stat -f%z "$file")
              if [ $size -gt 5242880 ]; then  # 5MB limit
                echo "❌ File $file exceeds size limit of 5MB"
                exit 1
              fi
            fi
          done

          # Check for binary files
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | while read file; do
            if [ -f "$file" ] && file "$file" | grep -q "binary"; then
              echo "❌ Binary file detected: $file"
              exit 1
            fi
          done

          # Check for suspicious patterns in modified files
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > changed_files.txt
          
          # Define patterns to check
          SUSPICIOUS_PATTERNS=(
            "crypto\."                    # Crypto operations
            "eval[\s]*\("                 # eval() calls
            "child_process"               # Child process operations
            "exec[A-Z][a-z]*\("          # Any exec* function calls
            "http[s]?\."                  # HTTP/HTTPS operations
            "net\."                       # Network operations
            "process\.env"                # Environment access
            "require\(['\"]child_process" # Child process requires
            "fs\."                        # File system operations
            "new\s+Function"              # Dynamic function creation
            "__proto__"                   # Prototype manipulation
            "Function\("                  # Function constructor
            "require\(['\"]\.\."         # Requiring outside directory
            "require\(['\"]~"            # Requiring from home directory
            "process\.binding"           # Low-level process bindings
            "v8\."                       # V8 engine access
            "vm\."                       # VM module operations
            "\.constructor\."            # Constructor access
            "Object\.prototype"          # Prototype manipulation
            "Object\.defineProperty"     # Property definition
            "Object\.setPrototypeOf"     # Prototype manipulation
          )
          
          # Check each pattern
          FOUND_PATTERNS=()
          for pattern in "${SUSPICIOUS_PATTERNS[@]}"; do
            if git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "$pattern"; then
              FOUND_PATTERNS+=("$pattern")
            fi
          done
          
          if [ ${#FOUND_PATTERNS[@]} -eq 0 ]; then
            echo "SECURITY_CHECK_RESULT=✅ No suspicious patterns found" >> $GITHUB_ENV
          else
            PATTERNS_LIST=$(printf "• %s\n" "${FOUND_PATTERNS[@]}")
            echo "SECURITY_CHECK_RESULT=⚠️ Review required - Found suspicious patterns:\n${PATTERNS_LIST}" >> $GITHUB_ENV
          fi
      
      - name: Setup environment
        uses: ./.github/actions/setup-environment
         
      - name: Deploy to Vercel
        id: deploy
        timeout-minutes: 15  # Prevent hanging deployments
        uses: ./.github/actions/deploy/vercel/development
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          pr-number: ${{ github.event.pull_request.number }}

      - name: Generate App ID
        id: generate-app-id
        uses: ./.github/actions/generate-app-id
        with:
          vercel_preview_url: ${{ steps.deploy.outputs.deployment-url }}
          deriv_api_token: ${{ secrets.DERIV_API_TOKEN }}
          deriv_app_id: ${{ secrets.DERIV_APP_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare preview URL
        id: preview-url
        uses: ./.github/actions/prepare-preview-url
        with:
          deployment-url: ${{ steps.deploy.outputs.deployment-url }}
          app-id: ${{ steps.generate-app-id.outputs.app-id }}

      - name: Add preview URL to pull request
        uses: actions/github-script@v6
        with:
          script: |
            const isFork = '${{ needs.security-check.outputs.is-fork }}' === 'true';
            const isAuthorized = '${{ needs.security-check.outputs.is-authorized }}' === 'true';
            
            let securityStatus = '';
            if (isFork) {
              securityStatus = `\n\n🔒 Security Status:
              - PR is from a fork repository
              - Author permission level: ${isAuthorized ? '✅ Authorized' : '⚠️ Requires Approval'}
              - Security checks: ${process.env.SECURITY_CHECK_RESULT || '✅ Passed'}
              
              Note: First-time contributors require maintainer approval for workflow runs.`;
            }
            
            github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✨ Preview deployment is ready at: ${{ steps.preview-url.outputs.url }}${securityStatus}`
            })

      # Cleanup old preview deployments
      - name: Cleanup old previews
        if: always()
        run: |
          if [ ! -z "${{ steps.deploy.outputs.deployment-url }}" ]; then
            echo "Cleaning up old preview deployments..."
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
              "https://api.vercel.com/v13/deployments/${{ steps.deploy.outputs.deployment-id }}"
          fi

      - name: Update deployment status
        uses: ./.github/actions/deployment-status
        if: success()  # Only mark success if all previous steps succeeded
        with:
          environment: 'preview'
          deployment-url: ${{ steps.preview-url.outputs.url }}
          sha: ${{ github.event.pull_request.head.sha }}
          status: 'success'
          description: '✨ Preview deployment completed'

      - name: Handle deployment failure
        if: failure()
        uses: ./.github/actions/deployment-status
        with:
          environment: 'preview'
          deployment-url: ${{ steps.preview-url.outputs.url }}
          sha: ${{ github.event.pull_request.head.sha }}
          status: 'failure'
          description: '❌ Preview deployment failed'
