name: Deploy Preview

on:
  pull_request_target:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: read
  pull-requests: write
  deployments: write
  id-token: write

concurrency:
  group: preview-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: development
  HUSKY: 0

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.preview-url.outputs.url }}
    steps:
      - name: Verify user
        uses: 'deriv-com/shared-actions/.github/actions/verify_user_in_organization@v1'
        with:
          username: ${{github.event.pull_request.user.login}}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        timeout-minutes: 3
         
      - name: Deploy to Vercel
        id: deploy
        uses: ./.github/actions/deploy/vercel/development
        timeout-minutes: 10
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          pr-number: ${{ github.event.pull_request.number }}

      - name: Generate App ID
        id: generate-app-id
        uses: ./.github/actions/generate-app-id
        timeout-minutes: 2
        with:
          vercel_preview_url: ${{ steps.deploy.outputs.deployment-url }}
          deriv_api_token: ${{ secrets.DERIV_API_TOKEN }}
          deriv_app_id: ${{ secrets.DERIV_APP_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare preview URL
        id: preview-url
        uses: ./.github/actions/prepare-preview-url
        with:
          deployment-url: ${{ steps.deploy.outputs.deployment-url }}
          app-id: ${{ steps.generate-app-id.outputs.app-id }}

      - name: Add preview URL to pull request
        uses: actions/github-script@v7
        with:
          script: |
            const deploymentUrl = '${{ steps.preview-url.outputs.url }}';
            const comment = `✨ Preview deployment is ready!
            
            🔗 Preview URL: ${deploymentUrl}
            📝 Commit: ${context.sha.substring(0, 7)}
            🕒 Deployed at: ${new Date().toISOString()}`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Update deployment status
        if: always()
        uses: ./.github/actions/deployment-status
        with:
          environment: 'preview'
          deployment-url: ${{ steps.preview-url.outputs.url }}
          sha: ${{ github.event.pull_request.head.sha }}
          status: ${{ job.status }}
          description: ${{ job.status == 'success' && '✨ Preview deployment completed' || '❌ Preview deployment failed' }}
